from django.contrib import admin
''' Here we register Webpages which use models.(Pages which take user input are registered here) '''
from home.models import contactus,hostus1,AryanHomestay,CosyRoom,BakshiHeritage,paradise,RiversedgeNest,EdenHomestay,Packiavilla,RestelStudio,UrbanNest,WalnutCottage,Shambhal,Bellevue,BirTerraces,ThinlayHomestay,ShumbukHomes,OrchidGlade,HeavotCaves,VillaC
from home.models import booktr,bookdb,booknz,bookp,bookgr,booksw
admin.site.register(contactus)
admin.site.register(AryanHomestay)
admin.site.register(hostus1)
admin.site.register(CosyRoom)
admin.site.register(BakshiHeritage)
admin.site.register(paradise)
admin.site.register(RiversedgeNest)
admin.site.register(EdenHomestay)
admin.site.register(Packiavilla)
admin.site.register(RestelStudio)
admin.site.register(UrbanNest)
admin.site.register(WalnutCottage)
admin.site.register(Shambhal)
admin.site.register(Bellevue)
admin.site.register(BirTerraces)
admin.site.register(ThinlayHomestay)
admin.site.register(ShumbukHomes)
admin.site.register(OrchidGlade)
admin.site.register(HeavotCaves)
admin.site.register(VillaC)
admin.site.register(booktr)
admin.site.register(bookdb)
admin.site.register(booknz)
admin.site.register(bookp)
admin.site.register(bookgr)
admin.site.register(booksw)
