# Generated by Django 3.1.8 on 2021-06-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stayus1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname1', models.CharField(max_length=122)),
                ('lastname1', models.CharField(max_length=122)),
                ('email1', models.CharField(max_length=122)),
                ('phone1', models.CharField(max_length=13)),
                ('adult1', models.CharField(max_length=13)),
                ('child1', models.CharField(max_length=13)),
                ('start1', models.DateField()),
                ('end1', models.DateField()),
                ('address1', models.TextField()),
                ('state1', models.CharField(max_length=13)),
                ('pin1', models.CharField(max_length=7)),
            ],
        ),
    ]
