# Generated by Django 3.1.8 on 2021-06-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_stayus1'),
    ]

    operations = [
        migrations.CreateModel(
            name='hostus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstnameh', models.CharField(max_length=122)),
                ('lastnameh', models.CharField(max_length=122)),
                ('emailh', models.CharField(max_length=122)),
                ('phoneh', models.CharField(max_length=13)),
                ('addressh', models.TextField()),
                ('stateh', models.CharField(max_length=13)),
                ('pinh', models.CharField(max_length=7)),
                ('date', models.DateField()),
            ],
        ),
    ]
