# Generated by Django 3.1.8 on 2021-06-04 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hostus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hostus',
            new_name='hostus1',
        ),
    ]
