# Generated by Django 3.1.8 on 2021-06-09 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_stayus1_otp1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stayus1',
            name='otp1',
        ),
    ]
