# Generated by Django 3.1.8 on 2021-06-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_stayus1_otp1'),
    ]

    operations = [
        migrations.CreateModel(
            name='stayus4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname4', models.CharField(max_length=122)),
                ('lastname4', models.CharField(max_length=122)),
                ('email4', models.CharField(max_length=122)),
                ('phone4', models.CharField(max_length=13)),
                ('adult4', models.CharField(max_length=13)),
                ('child4', models.CharField(max_length=13)),
                ('start4', models.DateField()),
                ('end4', models.DateField()),
                ('address4', models.TextField()),
                ('state4', models.CharField(max_length=13)),
                ('pin4', models.CharField(max_length=7)),
            ],
        ),
    ]
