# Generated by Django 3.1.8 on 2021-06-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_stayus10_stayus11_stayus12_stayus13_stayus14_stayus15_stayus16_stayus17_stayus18_stayus5_stayus6_sta'),
    ]

    operations = [
        migrations.CreateModel(
            name='LucknowCondominium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname4', models.CharField(max_length=122)),
                ('lastname4', models.CharField(max_length=122)),
                ('email4', models.CharField(max_length=122)),
                ('phone4', models.CharField(max_length=13)),
                ('adult4', models.CharField(max_length=13)),
                ('child4', models.CharField(max_length=13)),
                ('start4', models.DateField()),
                ('end4', models.DateField()),
                ('address4', models.TextField()),
                ('state4', models.CharField(max_length=13)),
                ('pin4', models.CharField(max_length=7)),
            ],
        ),
        migrations.RenameModel(
            old_name='stayus3',
            new_name='AryanHomestay',
        ),
        migrations.RenameModel(
            old_name='stayus4',
            new_name='BakshiHeritage',
        ),
        migrations.RenameModel(
            old_name='stayus1',
            new_name='CosyRoom',
        ),
        migrations.DeleteModel(
            name='stayus2',
        ),
        migrations.RenameField(
            model_name='aryanhomestay',
            old_name='address3',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='aryanhomestay',
            old_name='adult3',
            new_name='adult1',
        ),
        migrations.RenameField(
            model_name='aryanhomestay',
            old_name='child3',
            new_name='child1',
        ),
        migrations.RenameField(
            model_name='aryanhomestay',
            old_name='email3',
            new_name='email1',
        ),
        migrations.RenameField(
            model_name='aryanhomestay',
            old_name='end3',
            new_name='end1',
        ),
        migrations.RenameField(
            model_name='aryanhomestay',
            old_name='firstname3',
            new_name='firstname1',
        ),
        migrations.RenameField(
            model_name='aryanhomestay',
            old_name='lastname3',
            new_name='lastname1',
        ),
        migrations.RenameField(
            model_name='aryanhomestay',
            old_name='phone3',
            new_name='phone1',
        ),
        migrations.RenameField(
            model_name='aryanhomestay',
            old_name='pin3',
            new_name='pin1',
        ),
        migrations.RenameField(
            model_name='aryanhomestay',
            old_name='start3',
            new_name='start1',
        ),
        migrations.RenameField(
            model_name='aryanhomestay',
            old_name='state3',
            new_name='state1',
        ),
        migrations.RenameField(
            model_name='bakshiheritage',
            old_name='address4',
            new_name='address3',
        ),
        migrations.RenameField(
            model_name='bakshiheritage',
            old_name='adult4',
            new_name='adult3',
        ),
        migrations.RenameField(
            model_name='bakshiheritage',
            old_name='child4',
            new_name='child3',
        ),
        migrations.RenameField(
            model_name='bakshiheritage',
            old_name='email4',
            new_name='email3',
        ),
        migrations.RenameField(
            model_name='bakshiheritage',
            old_name='end4',
            new_name='end3',
        ),
        migrations.RenameField(
            model_name='bakshiheritage',
            old_name='firstname4',
            new_name='firstname3',
        ),
        migrations.RenameField(
            model_name='bakshiheritage',
            old_name='lastname4',
            new_name='lastname3',
        ),
        migrations.RenameField(
            model_name='bakshiheritage',
            old_name='phone4',
            new_name='phone3',
        ),
        migrations.RenameField(
            model_name='bakshiheritage',
            old_name='pin4',
            new_name='pin3',
        ),
        migrations.RenameField(
            model_name='bakshiheritage',
            old_name='start4',
            new_name='start3',
        ),
        migrations.RenameField(
            model_name='bakshiheritage',
            old_name='state4',
            new_name='state3',
        ),
        migrations.RenameField(
            model_name='cosyroom',
            old_name='address1',
            new_name='address2',
        ),
        migrations.RenameField(
            model_name='cosyroom',
            old_name='adult1',
            new_name='adult2',
        ),
        migrations.RenameField(
            model_name='cosyroom',
            old_name='child1',
            new_name='child2',
        ),
        migrations.RenameField(
            model_name='cosyroom',
            old_name='email1',
            new_name='email2',
        ),
        migrations.RenameField(
            model_name='cosyroom',
            old_name='end1',
            new_name='end2',
        ),
        migrations.RenameField(
            model_name='cosyroom',
            old_name='firstname1',
            new_name='firstname2',
        ),
        migrations.RenameField(
            model_name='cosyroom',
            old_name='lastname1',
            new_name='lastname2',
        ),
        migrations.RenameField(
            model_name='cosyroom',
            old_name='phone1',
            new_name='phone2',
        ),
        migrations.RenameField(
            model_name='cosyroom',
            old_name='pin1',
            new_name='pin2',
        ),
        migrations.RenameField(
            model_name='cosyroom',
            old_name='start1',
            new_name='start2',
        ),
        migrations.RenameField(
            model_name='cosyroom',
            old_name='state1',
            new_name='state2',
        ),
    ]
