# Generated by Django 3.1.8 on 2021-06-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_aryanhomestay_refid'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdenHomestay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname6', models.CharField(max_length=122)),
                ('lastname6', models.CharField(max_length=122)),
                ('email6', models.CharField(max_length=122)),
                ('phone6', models.CharField(max_length=13)),
                ('adult6', models.CharField(max_length=13)),
                ('child6', models.CharField(max_length=13)),
                ('start6', models.DateField()),
                ('end6', models.DateField()),
                ('address6', models.TextField()),
                ('state6', models.CharField(max_length=13)),
                ('pin6', models.CharField(max_length=7)),
                ('refid', models.IntegerField(default=0, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Packiavilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname7', models.CharField(max_length=122)),
                ('lastname7', models.CharField(max_length=122)),
                ('email7', models.CharField(max_length=122)),
                ('phone7', models.CharField(max_length=13)),
                ('adult7', models.CharField(max_length=13)),
                ('child7', models.CharField(max_length=13)),
                ('start7', models.DateField()),
                ('end7', models.DateField()),
                ('address7', models.TextField()),
                ('state7', models.CharField(max_length=13)),
                ('pin7', models.CharField(max_length=7)),
                ('refid', models.IntegerField(default=0, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='RiversedgeNest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname5', models.CharField(max_length=122)),
                ('lastname5', models.CharField(max_length=122)),
                ('email5', models.CharField(max_length=122)),
                ('phone5', models.CharField(max_length=13)),
                ('adult5', models.CharField(max_length=13)),
                ('child5', models.CharField(max_length=13)),
                ('start5', models.DateField()),
                ('end5', models.DateField()),
                ('address5', models.TextField()),
                ('state5', models.CharField(max_length=13)),
                ('pin5', models.CharField(max_length=7)),
                ('refid', models.IntegerField(default=0, verbose_name='')),
            ],
        ),
        migrations.DeleteModel(
            name='stayus5',
        ),
        migrations.DeleteModel(
            name='stayus6',
        ),
        migrations.DeleteModel(
            name='stayus7',
        ),
        migrations.AddField(
            model_name='bakshiheritage',
            name='refid',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='cosyroom',
            name='refid',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='lucknowcondominium',
            name='refid',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='stayus10',
            name='refid',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='stayus11',
            name='refid',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='stayus12',
            name='refid',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='stayus13',
            name='refid',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='stayus14',
            name='refid',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='stayus15',
            name='refid',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='stayus16',
            name='refid',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='stayus17',
            name='refid',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='stayus18',
            name='refid',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='stayus8',
            name='refid',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='stayus9',
            name='refid',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
    ]
