# Generated by Django 3.1.8 on 2021-06-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210613_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='dubaibook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstnamed', models.CharField(max_length=122)),
                ('lastnamed', models.CharField(max_length=122)),
                ('emaild', models.CharField(max_length=122)),
                ('phoned', models.CharField(max_length=13)),
                ('adultd', models.CharField(max_length=13)),
                ('childd', models.CharField(max_length=13)),
                ('bookd', models.DateField()),
                ('refid', models.IntegerField(default=0, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='grecebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstnameg', models.CharField(max_length=122)),
                ('lastnameg', models.CharField(max_length=122)),
                ('emailg', models.CharField(max_length=122)),
                ('phoneg', models.CharField(max_length=13)),
                ('adultg', models.CharField(max_length=13)),
                ('childg', models.CharField(max_length=13)),
                ('bookg', models.DateField()),
                ('refid', models.IntegerField(default=0, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='nzbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstnamen', models.CharField(max_length=122)),
                ('lastnamen', models.CharField(max_length=122)),
                ('emailn', models.CharField(max_length=122)),
                ('phonen', models.CharField(max_length=13)),
                ('adultn', models.CharField(max_length=13)),
                ('childn', models.CharField(max_length=13)),
                ('bookn', models.DateField()),
                ('refid', models.IntegerField(default=0, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='portugalbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstnamep', models.CharField(max_length=122)),
                ('lastnamep', models.CharField(max_length=122)),
                ('emailp', models.CharField(max_length=122)),
                ('phonep', models.CharField(max_length=13)),
                ('adultp', models.CharField(max_length=13)),
                ('childp', models.CharField(max_length=13)),
                ('bookp', models.DateField()),
                ('refid', models.IntegerField(default=0, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='swisbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstnames', models.CharField(max_length=122)),
                ('lastnames', models.CharField(max_length=122)),
                ('emails', models.CharField(max_length=122)),
                ('phones', models.CharField(max_length=13)),
                ('adults', models.CharField(max_length=13)),
                ('childs', models.CharField(max_length=13)),
                ('books', models.DateField()),
                ('refid', models.IntegerField(default=0, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='turkeybook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstnamet', models.CharField(max_length=122)),
                ('lastnamet', models.CharField(max_length=122)),
                ('emailt', models.CharField(max_length=122)),
                ('phonet', models.CharField(max_length=13)),
                ('adultt', models.CharField(max_length=13)),
                ('childt', models.CharField(max_length=13)),
                ('bookt', models.DateField()),
                ('refid', models.IntegerField(default=0, verbose_name='')),
            ],
        ),
    ]
