# Generated by Django 3.1.8 on 2021-06-13 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_dubaibook_grecebook_nzbook_portugalbook_swisbook_turkeybook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turkeybook',
            old_name='firstnamet',
            new_name='firstt',
        ),
        migrations.RenameField(
            model_name='turkeybook',
            old_name='lastnamet',
            new_name='lastt',
        ),
    ]
