# Generated by Django 3.1.8 on 2021-06-13 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210613_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turkeybook',
            old_name='adultt',
            new_name='adult19',
        ),
        migrations.RenameField(
            model_name='turkeybook',
            old_name='bookt',
            new_name='book19',
        ),
        migrations.RenameField(
            model_name='turkeybook',
            old_name='childt',
            new_name='child19',
        ),
        migrations.RenameField(
            model_name='turkeybook',
            old_name='emailt',
            new_name='email19',
        ),
        migrations.RenameField(
            model_name='turkeybook',
            old_name='firstt',
            new_name='firstname19',
        ),
        migrations.RenameField(
            model_name='turkeybook',
            old_name='lastt',
            new_name='lastname19',
        ),
        migrations.RenameField(
            model_name='turkeybook',
            old_name='phonet',
            new_name='phone19',
        ),
    ]
