# Generated by Django 3.1.8 on 2021-06-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210613_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turkeybook',
            name='adult19',
            field=models.CharField(default='user', max_length=13),
        ),
        migrations.AlterField(
            model_name='turkeybook',
            name='child19',
            field=models.CharField(default='user', max_length=13),
        ),
        migrations.AlterField(
            model_name='turkeybook',
            name='email19',
            field=models.CharField(default='user', max_length=122),
        ),
        migrations.AlterField(
            model_name='turkeybook',
            name='firstname19',
            field=models.CharField(default='user', max_length=122),
        ),
        migrations.AlterField(
            model_name='turkeybook',
            name='lastname19',
            field=models.CharField(default='user', max_length=122),
        ),
        migrations.AlterField(
            model_name='turkeybook',
            name='phone19',
            field=models.CharField(default='user', max_length=13),
        ),
    ]
