# Generated by Django 3.1.8 on 2021-06-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_bookturkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='stay19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname19', models.CharField(max_length=122)),
                ('lastname19', models.CharField(max_length=122)),
                ('email19', models.CharField(max_length=122)),
                ('phone19', models.CharField(max_length=13)),
                ('adult19', models.CharField(max_length=13)),
                ('child19', models.CharField(max_length=13)),
                ('start19', models.DateField()),
                ('end19', models.DateField()),
                ('address19', models.TextField()),
                ('state19', models.CharField(max_length=13)),
                ('pin19', models.CharField(max_length=7)),
                ('refid', models.IntegerField(default=0, verbose_name='')),
            ],
        ),
        migrations.AlterField(
            model_name='turkeybook',
            name='adult19',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='turkeybook',
            name='child19',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='turkeybook',
            name='email19',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='turkeybook',
            name='firstname19',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='turkeybook',
            name='lastname19',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='turkeybook',
            name='phone19',
            field=models.CharField(max_length=13),
        ),
    ]
