# Generated by Django 3.1.8 on 2021-06-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20210613_1602'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stay19',
            new_name='stayus19',
        ),
    ]
