# Generated by Django 3.1.8 on 2021-06-13 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20210613_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stayus19',
            name='end19',
        ),
    ]
