# Generated by Django 3.1.8 on 2021-06-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20210613_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname20', models.CharField(max_length=122)),
                ('lastname20', models.CharField(max_length=122)),
                ('email20', models.CharField(max_length=122)),
                ('phone20', models.CharField(max_length=13)),
                ('adult20', models.CharField(max_length=13)),
                ('child20', models.CharField(max_length=13)),
                ('start20', models.DateField()),
                ('address20', models.TextField()),
                ('state20', models.CharField(max_length=13)),
                ('pin20', models.CharField(max_length=7)),
                ('refid', models.IntegerField(default=0, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='bookgr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname23', models.CharField(max_length=122)),
                ('lastname23', models.CharField(max_length=122)),
                ('email23', models.CharField(max_length=122)),
                ('phone23', models.CharField(max_length=13)),
                ('adult23', models.CharField(max_length=13)),
                ('child23', models.CharField(max_length=13)),
                ('start23', models.DateField()),
                ('address23', models.TextField()),
                ('state23', models.CharField(max_length=13)),
                ('pin23', models.CharField(max_length=7)),
                ('refid', models.IntegerField(default=0, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='booknz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname21', models.CharField(max_length=122)),
                ('lastname21', models.CharField(max_length=122)),
                ('email21', models.CharField(max_length=122)),
                ('phone21', models.CharField(max_length=13)),
                ('adult21', models.CharField(max_length=13)),
                ('child21', models.CharField(max_length=13)),
                ('start21', models.DateField()),
                ('address21', models.TextField()),
                ('state21', models.CharField(max_length=13)),
                ('pin21', models.CharField(max_length=7)),
                ('refid', models.IntegerField(default=0, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='bookp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname22', models.CharField(max_length=122)),
                ('lastname22', models.CharField(max_length=122)),
                ('email22', models.CharField(max_length=122)),
                ('phone22', models.CharField(max_length=13)),
                ('adult22', models.CharField(max_length=13)),
                ('child22', models.CharField(max_length=13)),
                ('start22', models.DateField()),
                ('address22', models.TextField()),
                ('state22', models.CharField(max_length=13)),
                ('pin22', models.CharField(max_length=7)),
                ('refid', models.IntegerField(default=0, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='booksw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname24', models.CharField(max_length=122)),
                ('lastname24', models.CharField(max_length=122)),
                ('email24', models.CharField(max_length=122)),
                ('phone24', models.CharField(max_length=13)),
                ('adult24', models.CharField(max_length=13)),
                ('child24', models.CharField(max_length=13)),
                ('start24', models.DateField()),
                ('address24', models.TextField()),
                ('state24', models.CharField(max_length=13)),
                ('pin24', models.CharField(max_length=7)),
                ('refid', models.IntegerField(default=0, verbose_name='')),
            ],
        ),
        migrations.DeleteModel(
            name='bookturkey',
        ),
        migrations.DeleteModel(
            name='dubaibook',
        ),
        migrations.DeleteModel(
            name='grecebook',
        ),
        migrations.DeleteModel(
            name='nzbook',
        ),
        migrations.DeleteModel(
            name='portugalbook',
        ),
        migrations.DeleteModel(
            name='swisbook',
        ),
    ]
