# Generated by Django 3.1.8 on 2021-06-15 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20210613_1700'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LucknowCondominium',
            new_name='paradise',
        ),
    ]
